commands-on-login:
  - "say {player} has logged in!"
  - "warp spawn {player}"

commands-on-register:
  - "say {player} has registered!"
  - "warp tutorial {player}"

login-messages:
  - "§aWelcome back, {player}!"
  - "§eCheck out the new updates, {player}!"

register-messages:
  - "§bWelcome, {player}! Please check your email."
  - "§fMake sure to set up your profile."

send-login-messages: true
send-register-messages: true
run-login-commands: true
run-register-commands: true
command-delay: 1000  # 1 second delay for commands
message-delay: 1000  # 1 second delay for messages
command-cooldown: 60000  # 1-minute cooldown for commands
message-cooldown: 60000  # 1-minute cooldown for messages
