name: Build AuthMeCommands Plugin

on:
  push:
    branches:
      - main  # Trigger the build on pushing to the main branch (or another branch you prefer)
  pull_request:
    branches:
      - main  # Trigger the build when a pull request is created to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the build on a fresh Ubuntu VM
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2  # This fetches your code from GitHub to the CI environment
    
    - name: Set up JDK 21
      uses: actions/setup-java@v2  # This step sets up Java
      with:
        java-version: '21'  # Specifies that we are using JDK 21
    
    - name: Build with Maven
      run: mvn clean package -DskipTests  # Use Maven to build the plugin (adjust if you're using Gradle)
      
    # If you're using Gradle instead, use the following (uncomment this block):
    # - name: Build with Gradle
    #   run: ./gradlew build  # If you're using Gradle to build the plugin
    
    - name: Upload .jar to GitHub Release
      uses: softprops/action-gh-release@v1  # This uploads the generated .jar to the GitHub release page
      with:
        files: target/*.jar  # Adjust this path if you're using Gradle or another build directory
