name: Build AuthMeCommands

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adoptopenjdk'  # You can use "adoptopenjdk" or other distributions like "zulu"
        java-version: '21'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR file
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: AuthMeCommands
        path: target/AuthMeCommands-1.0-SNAPSHOT.jar
